openapi: 3.0.0
info:
  title: Messenger To Service
  description: Messenger에서 Messenger로의 Request입니다.
  version: 1.0.0
paths:
  /api/channels/{channel_id}:
    $ref: "./paths/ReadReceiptsEndpoints.yaml#/paths/~1api~1channels~1{channelId}"


