openapi: 3.0.0
info:
  title: Service
  description: Service는 Authentication/Authorization, RESTful API, DB와의 연결 등을 처리하는 백엔드 서비스입니다.
  version: 1.0.0

paths:
  /api/auth/login:
    $ref: "./paths/authEndpoints.yaml#/paths/~1api~1auth~1login"
