/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 성공 시 accessToken(1h) + refreshToken(7d) 발급. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogInRequest"];
                };
            };
            responses: {
                /** @description 로그인 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 이메일 혹은 pw 틀림 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 워크스페이스 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WorkspaceCreateRequest"];
                };
            };
            responses: {
                /** @description 워크스페이스 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceCreateResponse"];
                    };
                };
                /** @description Bad Request, 워크스페이스 이름 누락, 길이 제한 초과, 필수 필드 누락 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS003Error"];
                    };
                };
                /** @description Unauthorized, 로그인 하지 않은 상태에서 워크스페이스 생성 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Conflict, 동일한 이름의 워크스페이스가 존재함 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS001Error"];
                    };
                };
                /** @description Internal Server Error, DB 저장 중 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 로그인 후 자기가 속한 워크스페이스 목록 조회, 사이드바 렌더링에 사용 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그인 후 자기가 속한 워크스페이스 목록 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceGetResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 워크스페이스 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 워크스페이스 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDeleteResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 해당 워크스페이스 삭제 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 워크스페이스가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 워크스페이스 부분 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WorkspacePatchRequest"];
                };
            };
            responses: {
                /** @description 워크스페이스 부분 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspacePatchResponse"];
                    };
                };
                /** @description Bad Request, 유효하지 않은 값 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS003Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 해당 워크스페이스 수정 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 워크스페이스가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Conflict, 동일한 이름의 워크스페이스가 존재함 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS001Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/workspaces/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 목록 조회(내가 속한 + 공개 워크스페이스 커서 기반 조회) */
        get: {
            parameters: {
                query?: {
                    /** @description 검색 키워드 */
                    q?: string;
                    /** @description 조회 개수 */
                    limit?: number;
                    /** @description 커서 값 */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 워크스페이스 목록 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceSearchResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 조회 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 워크스페이스가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 채널 목록 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 채널 목록 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelListResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 조회 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 워크스페이스가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        put?: never;
        /** 워크스페이스 채널 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChannelCreateRequest"];
                };
            };
            responses: {
                /** @description 채널 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelCreateResponse"];
                    };
                };
                /** @description Bad Request, 필수 필드 누락 또는 유효하지 않은 값 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CH003Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 채널 생성 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Conflict, 동일한 이름의 채널이 존재함 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CH001Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 단일 채널 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    channelId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 단일 채널 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelDetailResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 조회 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 채널이 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CH002Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 채널 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    channelId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 채널 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelDeleteResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 삭제 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 채널이 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CH002Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 채널 부분 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    channelId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChannelPatchRequest"];
                };
            };
            responses: {
                /** @description 채널 부분 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelPatchResponse"];
                    };
                };
                /** @description Bad Request, 유효하지 않은 값 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CH003Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 수정 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 채널이 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CH002Error"];
                    };
                };
                /** @description Conflict, 동일한 이름의 채널이 존재함 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CH001Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 멤버 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 멤버 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceMemberListResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 조회 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 워크스페이스가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        put?: never;
        /** 닉네임 이용 워크스페이스로 멤버 초대 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberInviteRequest"];
                };
            };
            responses: {
                /** @description 멤버 초대 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceMemberInviteResponse"];
                    };
                };
                /** @description Bad Request, 유효하지 않은 닉네임 형식 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MBR004Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 멤버 초대 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Conflict, 이미 워크스페이스에 속한 멤버 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MBR002Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 워크스페이스 멤버 자진탈퇴 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 워크스페이스 탈퇴 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceMemberLeaveResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 탈퇴 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 워크스페이스 또는 멤버가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MBR005Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 워크스페이스 멤버 추방 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 워크스페이스 멤버 추방 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceMemberRemoveResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 추방 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 워크스페이스 또는 멤버가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MBR005Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 워크스페이스 멤버 일부 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberPatchRequest"];
                };
            };
            responses: {
                /** @description 멤버 일부 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceMemberPatchResponse"];
                    };
                };
                /** @description Bad Request, 유효하지 않은 값 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MBR004Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 수정 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 멤버가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MBR003Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/channels/{channelId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 채널 멤버 목록 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    channelId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 채널 멤버 목록 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelMemberListResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/channels/{channelId}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 채널 멤버 자진탈퇴 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    channelId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 채널 탈퇴 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelMemberLeaveResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 탈퇴 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 채널 또는 멤버가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MBR005Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/channels/{channelId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 채널 멤버 추방 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    channelId: number;
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 채널 멤버 추방 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelMemberRemoveResponse"];
                    };
                };
                /** @description Bad Request, 유효하지 않은 값 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MBR004Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Internal Server Error, 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 보드 목록 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 보드 목록 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BoardListResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Not Found, 워크스페이스가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        put?: never;
        /** 보드 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BoardCreateRequest"];
                };
            };
            responses: {
                /** @description 보드 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BoardCreateResponse"];
                    };
                };
                /** @description Bad Request, 필수 필드 누락 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS003Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/boards/{boardId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 태스크 목록 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    boardId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 태스크 목록 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskListResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Not Found, 보드가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        put?: never;
        /** 태스크 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    boardId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TaskCreateRequest"];
                };
            };
            responses: {
                /** @description 태스크 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskCreateResponse"];
                    };
                };
                /** @description Bad Request, 필수 필드 누락 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS003Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/boards/{boardId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 태스크 수정 (상태 변경, 담당자 변경, 칸반 이동 포함) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    boardId: number;
                    taskId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TaskUpdateRequest"];
                };
            };
            responses: {
                /** @description 태스크 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskUpdateResponse"];
                    };
                };
                /** @description Bad Request, 유효하지 않은 값 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS003Error"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 수정 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 태스크가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        post?: never;
        /** 태스크 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: number;
                    boardId: number;
                    taskId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 태스크 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskDeleteResponse"];
                    };
                };
                /** @description Unauthorized, 인증되지 않은 요청 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth003Error"];
                    };
                };
                /** @description Forbidden, 삭제 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Auth004Error"];
                    };
                };
                /** @description Not Found, 태스크가 존재하지 않음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WS002Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Server001Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 로그인 시 필요 정보 */
        LogInRequest: {
            /** @description ID */
            id: string;
            /** @description password */
            password: string;
        };
        /** @description 워크스페이스 생성 시 요청 */
        WorkspaceCreateRequest: {
            /** @description 워크스페이스 이름 */
            name: string;
            /** @description 공개/비공개 */
            isPrivate: boolean;
            /** @description 워크스페이스 설명 */
            description?: string;
            /** @description 워크스페이스 대표 이미지 */
            iconUrl?: string;
        };
        WorkspaceData: {
            /**
             * Format: int64
             * @description 워크스페이스 ID
             */
            id?: number;
            /** @description 워크스페이스 이름 */
            name?: string;
            /**
             * Format: int64
             * @description 워크스페이스 생성 소유자 ID
             */
            ownerId?: number;
            /** @description 공개/비공개 */
            isPrivate?: boolean;
            /** @description 워크스페이스 대표 이미지 URL */
            iconUrl?: string | null;
            /** @description 워크스페이스 설명 */
            description?: string | null;
            /**
             * Format: date-time
             * @description 생성일시
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 수정일시
             */
            updatedAt?: string;
        };
        WorkspaceCreateResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["WorkspaceData"];
            /** @example null */
            error?: unknown;
        };
        ErrorResponse: {
            /** @example false */
            success: boolean;
            /** @example null */
            data: unknown;
            error: {
                /**
                 * @description 에러 코드
                 * @example AUTH_001
                 */
                code: string;
                /**
                 * @description 클라이언트에 표시할 메시지
                 * @example 이메일 또는 비밀번호가 틀렸습니다
                 */
                message: string;
            };
        };
        /**
         * @description WS_003 | 400 | 유효하지 않은 워크스페이스 입력값
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "WS_003",
         *         "message": "워크스페이스 입력값이 유효하지 않습니다"
         *       }
         *     }
         */
        WS003Error: components["schemas"]["ErrorResponse"];
        /**
         * @description AUTH_003 | 401 | 토큰 만료 / 잘못된 토큰
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "AUTH_003",
         *         "message": "토큰이 만료되었습니다"
         *       }
         *     }
         */
        Auth003Error: components["schemas"]["ErrorResponse"];
        /**
         * @description WS_001 | 409 | 이미 사용중인 워크스페이스
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "WS_001",
         *         "message": "동일한 이름의 워크스페이스가 존재합니다"
         *       }
         *     }
         */
        WS001Error: components["schemas"]["ErrorResponse"];
        /**
         * @description SERVER_001 | 500 | 서버 내부 오류
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "SERVER_001",
         *         "message": "서버 내부 오류가 발생하였습니다"
         *       }
         *     }
         */
        Server001Error: components["schemas"]["ErrorResponse"];
        WorkspaceGetResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** Format: int64 */
                id?: number;
                name?: string;
                role?: string;
                iconUrl?: string | null;
            }[];
            /** @example null */
            error?: unknown;
        };
        WorkspaceDeleteResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @description 워크스페이스 삭제 메시지 */
                message?: string;
            };
            /** @example null */
            error?: unknown;
        };
        /**
         * @description AUTH_004 | 403 | 접근 권한 없음
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "AUTH_004",
         *         "message": "접근 권한이 없습니다"
         *       }
         *     }
         */
        Auth004Error: components["schemas"]["ErrorResponse"];
        /**
         * @description WS_002 | 404 | 찾을 수 없는 워크스페이스
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "WS_002",
         *         "message": "워크스페이스를 찾을 수 없습니다"
         *       }
         *     }
         */
        WS002Error: components["schemas"]["ErrorResponse"];
        /** @description 워크스페이스 부분수정 시 요청 */
        WorkspacePatchRequest: {
            /** @description 워크스페이스 이름 */
            name?: string;
            /** @description 공개/비공개 */
            isPrivate?: boolean;
            /** @description 워크스페이스 설명 */
            description?: string;
            /** @description 워크스페이스 대표 이미지 */
            iconUrl?: string;
        };
        WorkspacePatchResponse: components["schemas"]["WorkspaceCreateResponse"];
        WorkspaceSearchResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                data?: {
                    /** Format: int64 */
                    id?: number;
                    name?: string;
                    /** @description 워크스페이스 멤버 수 */
                    memberCount?: number;
                    isPrivate?: boolean;
                }[];
                nextCursor?: string | null;
                hasMore?: boolean;
            };
            /** @example null */
            error?: unknown;
        };
        ChannelData: {
            /**
             * Format: int64
             * @description 채널 ID
             */
            id?: number;
            /**
             * Format: int64
             * @description 워크스페이스 ID
             */
            workspaceId?: number;
            /** @description 채널 이름 */
            name?: string;
            /** @description 공개/비공개 */
            isPrivate?: boolean;
            /**
             * Format: date-time
             * @description 생성일시
             */
            createdAt?: string;
        };
        ChannelListResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["ChannelData"][];
            /** @example null */
            error?: unknown;
        };
        /** @description 채널 생성 시 요청 */
        ChannelCreateRequest: {
            /** @description 채널 이름 */
            name: string;
            /** @description 공개/비공개 */
            isPrivate: boolean;
        };
        ChannelCreateResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["ChannelData"];
            /** @example null */
            error?: unknown;
        };
        /**
         * @description CH_003 | 400 | 유효하지 않은 채널 입력값
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "CH_003",
         *         "message": "채널 입력값이 유효하지 않습니다"
         *       }
         *     }
         */
        CH003Error: components["schemas"]["ErrorResponse"];
        /**
         * @description CH_001 | 409 | 이미 사용중인 채널
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "CH_001",
         *         "message": "동일한 이름의 채널이 존재합니다"
         *       }
         *     }
         */
        CH001Error: components["schemas"]["ErrorResponse"];
        ChannelDetailResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["ChannelData"] & {
                /** @description 채널 멤버 수 */
                memberCount?: number;
            };
            /** @example null */
            error?: unknown;
        };
        /**
         * @description CH_002 | 404 | 찾을 수 없는 채널
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "CH_002",
         *         "message": "채널을 찾을 수 없습니다"
         *       }
         *     }
         */
        CH002Error: components["schemas"]["ErrorResponse"];
        ChannelDeleteResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @description 채널 삭제 메시지 */
                message?: string;
            };
            /** @example null */
            error?: unknown;
        };
        /** @description 채널 부분수정 시 요청 */
        ChannelPatchRequest: {
            /** @description 채널 이름 */
            name?: string;
            /** @description 공개/비공개 */
            isPrivate?: boolean;
        };
        ChannelPatchResponse: components["schemas"]["ChannelCreateResponse"];
        WorkspaceMemberData: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            /** @enum {string} */
            role?: "owner" | "admin" | "member";
            /** @enum {string} */
            statusCode?: "online" | "away" | "busy" | "offline" | "outside" | "remote";
        };
        WorkspaceMemberListResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["WorkspaceMemberData"][];
            /** @example null */
            error?: unknown;
        };
        /** @description 워크스페이스 멤버 초대 시 요청 */
        WorkspaceMemberInviteRequest: {
            /** @description 초대할 사용자의 닉네임 */
            nickname: string;
            /**
             * @description 멤버 역할
             * @default member
             * @enum {string}
             */
            role: "admin" | "member";
        };
        WorkspaceMemberInviteResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @example 초대 완료 */
                message?: string;
                /** Format: int64 */
                userId?: number;
                /** @enum {string} */
                role?: "owner" | "admin" | "member";
            };
            /** @example null */
            error?: unknown;
        };
        /**
         * @description MBR_004 | 400 | 유효하지 않은 멤버 입력값
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "MBR_004",
         *         "message": "멤버 입력값이 유효하지 않습니다"
         *       }
         *     }
         */
        MBR004Error: components["schemas"]["ErrorResponse"];
        /**
         * @description MBR_002 | 409 | 이미 워크스페이스에 속한 멤버
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "MBR_002",
         *         "message": "이미 워크스페이스에 속한 멤버입니다"
         *       }
         *     }
         */
        MBR002Error: components["schemas"]["ErrorResponse"];
        WorkspaceMemberLeaveResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @description 워크스페이스 탈퇴 메시지 */
                message?: string;
            };
            /** @example null */
            error?: unknown;
        };
        /**
         * @description MBR_005 | 404 | 찾을 수 없는 워크스페이스 또는 채널 또는 멤버
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "MBR_005",
         *         "message": "워크스페이스 또는 채널 또는 멤버를 찾을 수 없습니다"
         *       }
         *     }
         */
        MBR005Error: components["schemas"]["ErrorResponse"];
        WorkspaceMemberRemoveResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @description 워크스페이스 멤버 추방 메시지 */
                message?: string;
            };
            /** @example null */
            error?: unknown;
        };
        /** @description 워크스페이스 멤버 부분 수정 시 요청 */
        WorkspaceMemberPatchRequest: {
            /**
             * @description 변경할 멤버 역할
             * @enum {string}
             */
            role?: "admin" | "member";
        };
        WorkspaceMemberPatchResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["WorkspaceMemberData"];
            /** @example null */
            error?: unknown;
        };
        /**
         * @description MBR_003 | 404 | 찾을 수 없는 멤버
         * @example {
         *       "success": false,
         *       "data": null,
         *       "error": {
         *         "code": "MBR_003",
         *         "message": "멤버를 찾을 수 없습니다"
         *       }
         *     }
         */
        MBR003Error: components["schemas"]["ErrorResponse"];
        ChannelMemberData: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            /** @enum {string} */
            role?: "admin" | "member";
        };
        ChannelMemberListResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["ChannelMemberData"][];
            /** @example null */
            error?: unknown;
        };
        ChannelMemberLeaveResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @description 채널 탈퇴 메시지 */
                message?: string;
            };
            /** @example null */
            error?: unknown;
        };
        ChannelMemberRemoveResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @description 채널 멤버 추방 메시지 */
                message?: string;
            };
            /** @example null */
            error?: unknown;
        };
        BoardListResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            workspaceId?: number;
            /** Format: date-time */
            createdAt?: string;
        }[];
        BoardCreateRequest: {
            /** @description 보드 이름 */
            name: string;
        };
        BoardCreateResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            workspaceId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        TaskListResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            boardId?: number;
            title?: string;
            /** @enum {string} */
            status?: "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
            /** Format: int64 */
            assigneeId?: number;
            /** @enum {string} */
            priority?: "high" | "medium" | "low";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        }[];
        TaskCreateRequest: {
            /** @description 태스크 제목 */
            title: string;
            /**
             * @description 태스크 상태
             * @enum {string}
             */
            status: "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
            /**
             * Format: int64
             * @description 담당자 userId
             */
            assigneeId?: number;
            /**
             * @description 우선순위
             * @enum {string}
             */
            priority?: "high" | "medium" | "low";
        };
        TaskCreateResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            boardId?: number;
            title?: string;
            /** @enum {string} */
            status?: "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
            /** Format: int64 */
            assigneeId?: number;
            /** @enum {string} */
            priority?: "high" | "medium" | "low";
            /** Format: date-time */
            createdAt?: string;
        };
        TaskUpdateRequest: {
            /** @description 태스크 제목 */
            title?: string;
            /**
             * @description 태스크 상태 (칸반 컬럼 이동시 변경)
             * @enum {string}
             */
            status?: "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
            /**
             * Format: int64
             * @description 담당자 userId
             */
            assigneeId?: number;
            /**
             * @description 우선순위
             * @enum {string}
             */
            priority?: "high" | "medium" | "low";
        };
        TaskUpdateResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** @enum {string} */
            status?: "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
            /** Format: int64 */
            assigneeId?: number;
            /** @enum {string} */
            priority?: "high" | "medium" | "low";
            /** Format: date-time */
            updatedAt?: string;
        };
        TaskDeleteResponse: {
            /** Format: int64 */
            id?: number;
            /** @example 태스크가 삭제되었습니다. */
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
